TOC
d1mnewz/interviews pull request #6
Opened 2019-06-12 22:48 UTC by babayK0

Added table of contents for better document navigation

2019-06-16 10:46 UTC, d1mnewz commented
The document itself has formatting issues. This PR makes sense to me because I had to introduce TOC at some moment of time.
However 
```
[_^ back to TOC^_](#table-of-contents)
```
this constantly repeating line seems to add more noise than value. I would be happy to accept this PR without it. 
Also, as a side issue, we can fix formatting in the document since most likely it doesn't correspond to the syntax of [MD-language](https://daringfireball.net/projects/markdown/syntax). I can do that by myself using VS Code markdown extensions which highlights syntax errors, otherwise, you can do that yourself but in a separate PR, please.

Thanks for your contribution!

2019-06-17 12:27 UTC, babayK0 commented
@d1mnewz `[_^ back to TOC^_](#table-of-contents)` deleted !

2019-06-17 12:35 UTC, d1mnewz requested changes

2019-06-17 12:35 UTC, d1mnewz commented on README.md
> +[_^ back to TOC^_](#table-of-contents)
@babayK0 Why should we leave this one?

2019-06-17 12:36 UTC, babayK0 commented on README.md
> +[_^ back to TOC^_](#table-of-contents)
@d1mnewz my bad. wait sec

2019-06-17 12:41 UTC, d1mnewz approved these changes

2019-06-17 12:42 UTC, d1mnewz commented
Nice! Thanks for your contribution!

2019-06-17 12:42 UTC, merged